version: '3.6'
services:
  java:
    build: ./docker/java/
#    ports:
#      - 8080:8080
    tty: true
    volumes:
      - ./src/java:/usr/src/java:cached

  cpp:
    build: ./docker/cpp/
#    ports:
#      - 8080:8080
    tty: true
    volumes:
      - ./src/cpp:/usr/src/:cached

  php-apache:
    build: ./docker/php/
    container_name: php-apache
    ports:
      - '8082:80'
    volumes:
      - ./src/php:/var/www/html