all:
	make javac
	make java

javac:
	cd ../ && javac section5/sample5_1/staticMethod/Main.java
	cd ../ && javac section5/sample5_1/pretendStaticMethod/Main.java
	cd ../ && javac section5/sample5_2/badGiftPoint/Main.java
	cd ../ && javac section5/sample5_2/goodGiftPoint/Main.java
	cd ../ && javac section5/sample5_4/badActorManager/Main.java
	cd ../ && javac section5/sample5_4/goodActorManager/Main.java
	cd ../ && javac section5/sample5_5/badMoney/Main.java
	cd ../ && javac section5/sample5_5/goodMoney/Main.java
	cd ../ && javac section5/sample5_5/badMagic/Main.java
	cd ../ && javac section5/sample5_5/goodMagic/Main.java
	cd ../ && javac section5/sample5_6/useMethodChain/Main.java
	cd ../ && javac section5/summary/notRefactor/Main.java

java:
	echo "\n\nsample5_1.....staticMethod\n"
	cd ../ && java section5/sample5_1/staticMethod/Main
	echo "\n\nsample5_1.....pretendStaticMethod\n"
	cd ../ && java section5/sample5_1/pretendStaticMethod/Main
	echo "\n\nsample5_2.....badGiftPoint\n"
	cd ../ && java section5/sample5_2/badGiftPoint/Main
	echo "\n\nsample5_2.....goodGiftPoint\n"
	cd ../ && java section5/sample5_2/goodGiftPoint/Main
	echo "\n\nsample5_4.....badActorManager\n"
	cd ../ && java section5/sample5_4/badActorManager/Main
	echo "\n\nsample5_4.....goodActorManager\n"
	cd ../ && java section5/sample5_4/goodActorManager/Main
	echo "\n\nsample5_5.....badMoney\n"
	cd ../ && java section5/sample5_5/badMoney/Main
	echo "\n\nsample5_5.....goodMoney\n"
	cd ../ && java section5/sample5_5/goodMoney/Main
	echo "\n\nsample5_5.....badMagic\n"
	cd ../ && java section5/sample5_5/badMagic/Main
	echo "\n\nsample5_5.....goodMagic\n"
	cd ../ && java section5/sample5_5/goodMagic/Main
	echo "\n\nsample5_6.....useMethodChain\n"
	cd ../ && java section5/sample5_6/useMethodChain/Main
	echo "\n\nsummary.....notRefactor\n"
	cd ../ && java section5/summary/notRefactor/Main
